version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
      tag: '12.14.1'
    steps:
      - checkout
      - setup_remote_docker
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run test
      - store_artifacts:
          path: ./test/artifacts
workflows:
  version: 2
  build-and-push:
    jobs:
      - build:
          context: dockerhub