version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - setup_remote_docker
workflows:
  version: 2
  build-and-push:
    jobs:
      - build:
          context: dockerhub